### PR TITLE
 CORE_V_MCU high level design specs

### PR DESCRIPTION
**Pull request by cst-rameez**
Adding high level design specs for the IPs which have insufficient information in core_v_mcu user manual https://docs.openhwgroup.org/projects/core-v-mcu/ 

Following are CORE-V-MCU IP blocks whose documents are updated:
[APB Advanced Timer](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_adv_timer.html)
[APB SoC Controller](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_soc_ctrl.html)
[APB PLL Interface](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_fll_if.html)
[APB_GPIO](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_gpio.html)
[APB Timer](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_timer.html)
[ABP I2C Slave](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_i2cs.html)
[APB Event Control](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/apb_event_cntrl.html)
[UDMA CAMERA Interface](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/udma_cam.html)
[UDMA SD Card Interface](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/ip-blocks/udma_sdio.html)

### CODE REVIEW

**Comment by cst-rameez** [comment]
@MikeOpenHWGroup, I would like to add you as the reviewer here.

**Comment by DBees** [comment]
Hi @cst-rameez thank you so much for this work. Actually however the correct place to vector these documentation updates would be on the https://github.com/openhwgroup/core-v-mcu/tree/master/docs repo where the documentation files are written in .rst
Suggest that we setup a quick chat to chart next steps

**Comment by PaoloS02** [comment]
Any updates on this?

**Comment by MikeOpenHWGroup** [comment]
!  Completely forgot about this one - thanks for the gentle prod @PaoloS02.

These updates have been contributed to the [CORE-V-MCU repository](https://github.com/openhwgroup/core-v-mcu/pull/328) and are now integrated into the [User Manual](https://docs.openhwgroup.org/projects/core-v-mcu/).  I forgot to close this one.  (Will do so now.)

**Pull request closed without merging**
