### PR TITLE
Update CV32E41P Project proposal

### PR DESCRIPTION
**Pull request by abukharmeh**
Hi @DBees 

This is my updated project proposal for 41p reflecting yesterday presentation, could you please review it and let me know if there is anything missing ? 

The CI is not happy as my email address was changed, I will sort it out soon

Thanks,
Ibrahim

### CODE REVIEW

**Comment by abukharmeh** [comment]
Hi @DBees , 
This is my updated project proposal for 41P reflecting yesterday presentation, could you please review it and let me know if there is anything missing ? 
My email address got changed that's why CI is not happy, I will sort it out soon
Thanks,
Ibrahim

**Comment by DBees** [comment]
Just starting reviewing @abukharmeh , will finish Wednesday

**Comment by DBees** [comment]
@abukharmeh I think this PL proposal needs a little more effort. Many of the normally used fields are missing. Here is a summary ttps://docs.google.com/spreadsheets/d/1n1BlmlRya5xlrnOT711vs-MAzRec9fkLBqJofZewEj8/edit#gid=0. Perhaps we can setup a review meeting to got through this.

**Comment by abukharmeh** [comment]
@MarkHillHuawei Will create a new PR that will supercede this one

**Pull request closed without merging**
