### PR TITLE
Updated E41P Project Proposal

### PR DESCRIPTION
**Pull request by MarkHillHuawei**
Here are the updates to the E41P project proposal

### CODE REVIEW

**Comment by DBees** [comment]
@MarkHillHuawei @MikeOpenHWGroup This looks good. Thanks for the pull request. The only thing that should be changed is the title of the file. Instead of
[Project-Descriptions-and-Plans/CV32E41P/CV32E41P-project-proposal.md]

we should call it

[Project-Descriptions-and-Plans/CV32E41P/CV32E41P-Project-Launch-Proposal.md] so that people know it is the Project Launch document

**Review by tariqkurd-repo — APPROVED** [review]
Zce should be Zc
Zc doesn't include any 32-bit encodings.

**Comment by MarkHillHuawei** [comment]
OK I have made the requested changes, please let me know fo you spot anything else.

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
Thanks @MarkHillHuawei.  Merging...

**Pull request merged**
