### PR TITLE
Create CV32E40Pv2_not_verified_features.xlsx

### PR DESCRIPTION
**Pull request by XavierAubert**
Added a file that contains more informations on verification limitations and features not verified.

Feel free to tell me if there is anything missing or if I am not commiting in the right place

### CODE REVIEW

**Review by MikeOpenHWGroup — CHANGES_REQUESTED** [review]
Thanks for creating this document @XavierAubert!  I would ask for one change.  In cell F7 it says:
```
RTL freeze criteria for Dolphin Desgin but not for OHG
```
That is technically correct (except for the typo in `Design` :wink:), but could expand it to say:
```
RTL freeze criteria for Dolphin Design but not for OpenHW Group.  FSM Transition and State are encompassed by Branch plus Condition code coverage.
```

**Comment by MikeOpenHWGroup** [comment]
> For instance in the controller there are 2 "dead states"

Interesting point.  My statement assumes that there are no dead states.

**Comment by pascalgouedo** [comment]
Could FSM DEAD STATES and FSM UNREACHABLE TRANSITION be RTL Freeze blocking points?
Not mentioned in RTL checklist today but could improve the RTL quality...

But too late for CV32E40Pv2!

**Comment by XavierAubert** [comment]
I corrected the typo and added "plus Statements" to your words "", so at least it encompass as well unreachable states. 
Regarding dead ends, for me, it is why 100% FSM coverage is required at Dolphin ;)

**Pull request merged**
