### PR TITLE
CV-Mesh PC/PL

### PR DESCRIPTION
**Pull request by Jbalkind**

### CODE REVIEW

**Comment by DBees** [comment]
@Jbalkind thank you for the improvements and presenting the doc at TWG. Great job. One further improvement to the PL that I think would be helpful is to itemize the bridges that will be brought in at TRL3 as part of Component 5

**Comment by Jbalkind** [comment]
Alright I changed the wording to specify that they are P-Mesh bridges to/from AXI and AXI-Lite.

**Comment by DBees** [comment]
thanks @Jbalkind will proceed with the ballot asap

**Comment by MikeOpenHWGroup** [comment]
@DBees, should we not merge these docs in before the vote?

**Comment by DBees** [comment]
@MikeOpenHWGroup the sequence I've been using is pull request - vote - then merge, Vote has now passed

**Pull request merged**
