### PR TITLE
Move TRL-5 reports from CORE-V-VERIF to PROGRAMS

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
The TRL-5 reports for the CV32E40P are currently stored in CORE-V-VERIF which is arguably the wrong place for them.

### CODE REVIEW

**Comment by DBees** [comment]
@MikeOpenHWGroup rather than further expanding the milestones folder to have reams of project specific data, I'm wondering if we should instead put project specific milestones in the Project-Descriptions-and-Plans area (there should be 1 folder for each project). 
Then, we can relabel the current milestones folder as milestoneTemplates and keep only the templates there.

**Comment by MikeOpenHWGroup** [comment]
In this pull-request, the directory structure is like this:
```
programs
   └── milestones
       ├── README.md
       ├── templates
       └── CV32E40P
           ├── README.md
           ├── Reports
           │   └── cv32e40p
           │       ├── 2020-11-02
           │       ├── 2020-11-12
           │       ├── 2020-11-17
           │       ├── 2020-11-19
           │       ├── 2020-11-23
           │       ├── 2020-11-24
           │       ├── 2020-12-15
           │       ├── index.html
           │       └── Waivers
           └── RTL_Freeze_v1.0.0
               ├── DesignChecklist.md
               ├── ...other_checklists.md
               └── Verification_openissues.md
```
 The "reams of data" is under the `programs/milestones/CV32E40P/Reports` directory, so you only see it if you go to that specific directory.  Under [programs/milestones](https://github.com/MikeOpenHWGroup/programs/tree/e40p_reports/milestones) all you see is `CV32E40P`.

**Comment by DBees** [comment]
The point is that the project-descriptions-and-plans contains gate information per project already. Milestones data seems highly related.

**Comment by MikeOpenHWGroup** [comment]
So you'd like to put the milestones directory under `project-descriptions-and-plans `?

**Comment by DBees** [comment]
I think so. (Ideally we could rename project-descriptions-and-plans to project-descriptions-plans-milestones  But that would break a lot of links.) The advantage is that gate/milestone data would be grouped in a single place

**Pull request merged**
